"""
SEO change implementer.

Takes Claude's structured recommendations and applies them
directly to the HTML files. Creates a branch and PR for review.
"""

import json
import os
import re
import subprocess

import anthropic

from config import CLAUDE_MODEL, EXISTING_PAGES, MAX_TOKENS, SITE_URL, SUBURBS_TIER1, SUBURBS_TIER2


def generate_changes(analysis, repo_root=None):
    """
    Send analysis to Claude and get back structured changes to implement.

    Returns list of dicts:
        {file, change_type, old_value, new_value, description}
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("   ⚠ ANTHROPIC_API_KEY not set — skipping implementation")
        return []

    # Read current title/meta from HTML files so Claude knows exact values
    current_tags = _read_current_tags(repo_root) if repo_root else {}

    client = anthropic.Anthropic(api_key=api_key)

    system_prompt = _build_system_prompt(current_tags)
    user_prompt = _build_change_request(analysis)

    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=MAX_TOKENS,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )

    return _parse_changes(message.content[0].text)


def apply_changes(changes, repo_root):
    """
    Apply the list of changes to HTML files.

    Returns list of successfully applied changes.
    """
    applied = []

    for change in changes:
        file_rel = change["file"].lstrip("/")

        # Handle homepage — "/" maps to index.html
        if not file_rel or file_rel == "/":
            file_rel = "index.html"

        filepath = os.path.join(repo_root, file_rel)

        # Handle new_file type — file already written to disk by caller, just stage it
        if change.get("change_type") == "new_file":
            if os.path.isfile(filepath):
                applied.append(change)
                print(f"   ✓ new_file: {file_rel}")
            else:
                print(f"   ⚠ new_file declared but not found: {filepath}")
            continue

        # Must be an HTML file for all other change types
        if not file_rel.endswith(".html"):
            print(f"   ⚠ Skipping non-HTML file: {file_rel}")
            continue

        if not os.path.isfile(filepath):
            print(f"   ⚠ File not found: {filepath}")
            continue

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        old = change["old_value"]
        new = change["new_value"]

        if old not in content:
            # Try case-insensitive match for meta/title tags
            pattern = re.compile(re.escape(old), re.IGNORECASE)
            if pattern.search(content):
                content = pattern.sub(new, content, count=1)
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                applied.append(change)
                print(f"   ✓ {change['change_type']}: {change['file']} (case-insensitive)")
            else:
                print(f"   ⚠ Could not find old value in {change['file']}")
        else:
            content = content.replace(old, new, 1)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            applied.append(change)
            print(f"   ✓ {change['change_type']}: {change['file']}")

    return applied


def create_pr(changes, repo_root):
    """
    Create a git branch, commit changes, push, and open a PR.

    Returns (pr_url, pr_number) or (None, None) on failure.
    """
    from datetime import datetime

    date_str = datetime.now().strftime("%Y-%m-%d")
    time_str = datetime.now().strftime("%H%M")
    branch_name = f"seo-updates-{date_str}-{time_str}"

    try:
        _run_git(repo_root, "checkout", "-b", branch_name)

        # Stage only the changed HTML files
        changed_files = list(set(c["file"].lstrip("/") for c in changes))
        for f in changed_files:
            _run_git(repo_root, "add", f)

        # Build commit message
        summary_lines = [f"  - {c['description']}" for c in changes[:10]]
        if len(changes) > 10:
            summary_lines.append(f"  - ...and {len(changes) - 10} more")

        commit_msg = (
            f"SEO optimizations — {date_str}\n\n"
            + "\n".join(summary_lines)
            + "\n\nGenerated by MK Painting SEO Agent"
        )

        _run_git(repo_root, "commit", "-m", commit_msg)
        _run_git(repo_root, "push", "-u", "origin", branch_name)

        # Create PR via gh CLI
        pr_body = _build_pr_body(changes)
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", f"SEO: title/meta optimizations — {date_str}",
                "--body", pr_body,
                "--base", "main",
                "--head", branch_name,
            ],
            capture_output=True, text=True, cwd=repo_root,
        )

        if result.returncode == 0:
            pr_url = result.stdout.strip()
            # Extract PR number from URL
            pr_number = pr_url.rstrip("/").split("/")[-1]
            return pr_url, pr_number

        print(f"   ⚠ PR creation failed: {result.stderr}")
        return None, None

    except Exception as e:
        print(f"   ⚠ Git/PR error: {e}")
        return None, None

    finally:
        # Always switch back to main
        try:
            _run_git(repo_root, "checkout", "main")
        except Exception:
            pass


def _run_git(repo_root, *args):
    """Run a git command in the repo root."""
    result = subprocess.run(
        ["git"] + list(args),
        capture_output=True, text=True, cwd=repo_root,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr}")
    return result.stdout.strip()


def _read_current_tags(repo_root):
    """Read the current <title> and <meta description> from each HTML page."""
    tags = {}

    for slug in EXISTING_PAGES:
        file_rel = slug.lstrip("/")
        if not file_rel:
            file_rel = "index.html"
        if not file_rel.endswith(".html"):
            continue

        filepath = os.path.join(repo_root, file_rel)
        if not os.path.isfile(filepath):
            continue

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        # Extract <title>...</title>
        title_match = re.search(r"<title>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
        # Extract <meta name="description" content="...">
        meta_match = re.search(
            r'<meta\s+name=["\']description["\']\s+content=["\']([^"\']*)["\']',
            content, re.IGNORECASE,
        )

        tags[slug] = {
            "file": file_rel,
            "title": title_match.group(0) if title_match else None,
            "title_text": title_match.group(1).strip() if title_match else None,
            "meta": meta_match.group(0) if meta_match else None,
            "meta_text": meta_match.group(1).strip() if meta_match else None,
        }

    return tags


def _build_system_prompt(current_tags=None):
    pages_info = []
    for slug, kw in EXISTING_PAGES.items():
        line = f"- `{slug}` → target: \"{kw}\""
        if current_tags and slug in current_tags:
            t = current_tags[slug]
            if t["title"]:
                line += f"\n  Current title: `{t['title']}`"
            if t["meta"]:
                line += f"\n  Current meta: `{t['meta']}`"
        pages_info.append(line)

    pages_str = "\n".join(pages_info)

    return f"""You are an SEO implementation agent for M&K Painting Services ({SITE_URL}).

Existing pages, their target keywords, and CURRENT HTML tags:
{pages_str}

Your job is to output SPECIFIC changes to HTML files based on GSC performance data.

CRITICAL RULES:
- Only suggest title tag, meta description changes, and FAQ schema JSON-LD injection
- Output valid JSON array — no markdown, no explanation, just the JSON
- Each change must have: file, change_type, old_value, new_value, description
- old_value must be the EXACT current HTML string copied from above — character for character
- new_value must be the replacement HTML string
- For title changes: old_value = `<title>Current Title</title>`, new_value = `<title>New Title</title>`
- For meta changes: old_value = the full `<meta name="description" content="...">` tag, new_value = the new full tag
- For FAQ schema: change_type = "faq_schema", old_value = `</head>`, new_value = `<script type="application/ld+json">...valid schema...</script>\n</head>`.
- For Conversational Q&A (GEO): change_type = "conversational_qa", old_value = `</footer>`, new_value = `<div class="geo-qa" style="padding: 2rem 0; background: #f9f9f9; text-align: center;"><h2>Frequently Asked Questions</h2>...Q&A text formatted clearly for LLMs...</div>\n</footer>`
- For H1 changes: change_type = "h1", old_value = the exact `<h1>...</h1>` tag, new_value = the new `<h1>...</h1>` tag with better keyword targeting
- For internal links: change_type = "internal_link", old_value = an existing `<p>` or `<a>` tag, new_value = same element with an added or improved internal link
- For meta_fix (too-long tags): change_type = "meta_fix", old_value = the current too-long tag, new_value = trimmed version within character limits
- Title tags must be under 60 characters
- Meta descriptions must be 120-155 characters
- Suggest changes for CTR problems, Striking Distance keywords, AND any too-long meta tags listed
- Maximum 10 changes per run — focus on highest impact first
- The "file" field must be the HTML filename like "west-lakes.html" (not a slug like "/west-lakes.html")"""


def _build_change_request(analysis):
    parts = ["Here is today's GSC analysis. Output a JSON array of changes to implement.\n"]

    # CTR gaps
    ctr = analysis.get("ctr_gaps", [])[:10]
    if ctr:
        parts.append("**CTR Gaps (underperforming vs benchmark):**")
        for g in ctr:
            parts.append(
                f"- \"{g['query']}\" — pos {g['position']}, CTR {g['ctr']:.1%} "
                f"vs expected {g['expected_ctr']:.0%}, +{g['potential_clicks']} potential clicks"
            )

    # Zero click
    zc = analysis.get("zero_click", [])[:5]
    if zc:
        parts.append("\n**Zero-Click (impressions but no clicks):**")
        for z in zc:
            parts.append(f"- \"{z['query']}\" — {z['impressions']} imp, pos {z['position']}")

    # Striking distance
    sd = analysis.get("striking_distance", [])[:5]
    if sd:
        parts.append("\n**Striking Distance (pos 4-15):**")
        for kw in sd:
            parts.append(
                f"- \"{kw['query']}\" — pos {kw['position']}, {kw['impressions']} imp"
            )

    parts.append(
        '\n\nOutput format — JSON array only, no markdown:\n'
        '[{"file": "page.html", "change_type": "title", '
        '"old_value": "<title>Old Title</title>", '
        '"new_value": "<title>New Title</title>", '
        '"description": "Why this change helps"}, '
        '{"file": "page.html", "change_type": "faq_schema", '
        '"old_value": "</head>", '
        '"new_value": "<script type=\\"application/ld+json\\">...</script>\\n</head>", '
        '"description": "Added FAQ schema to boost CTR for striking distance keyword"}, '
        '{"file": "page.html", "change_type": "conversational_qa", '
        '"old_value": "</footer>", '
        '"new_value": "<div class=\\"geo-qa\\">...</div>\\n</footer>", '
        '"description": "Added conversational structured answers for LLM AI ingestion"}]'
    )

    return "\n".join(parts)


def _parse_changes(text):
    """Parse Claude's response into a list of change dicts."""
    # Try to find JSON array in the response
    text = text.strip()

    # Remove markdown code fences if present
    if "```" in text:
        match = re.search(r"```(?:json)?\s*(\[.*?\])\s*```", text, re.DOTALL)
        if match:
            text = match.group(1)

    # Try to find a JSON array
    start = text.find("[")
    end = text.rfind("]") + 1
    if start >= 0 and end > start:
        text = text[start:end]

    try:
        changes = json.loads(text)
        if not isinstance(changes, list):
            return []

        # Validate each change has required fields
        valid = []
        for c in changes:
            if all(k in c for k in ("file", "change_type", "old_value", "new_value", "description")):
                valid.append(c)

        return valid[:10]  # Max 10 changes per run

    except json.JSONDecodeError:
        print(f"   ⚠ Could not parse Claude's response as JSON")
        return []



# ── New page generation ──────────────────────────────────────────────────────


def pick_best_new_page(analysis, repo_root):
    """
    Pick the best new page opportunity from the analysis.

    Considers both suburb opportunities (pure geographic) and
    missing pages (service × suburb combos).

    Returns dict with suburb, keyword, filename, template_type or None.
    """
    existing_slugs = set(EXISTING_PAGES.keys())
    candidates = []

    # 1. Suburb opportunities (geographic pages like /tea-tree-gully.html)
    for opp in analysis.get("suburb_opportunities", []):
        suburb = opp["suburb"]
        slug = f"/{suburb.replace(' ', '-')}.html"
        if slug not in existing_slugs and not os.path.isfile(os.path.join(repo_root, slug.lstrip("/"))):
            queries_text = " ".join(opp.get("top_queries", []))
            is_commercial = any(w in queries_text for w in ["commercial", "industrial", "warehouse", "office"])
            candidates.append({
                "suburb": suburb,
                "impressions": opp["impressions"],
                "clicks": opp.get("clicks", 0),
                "top_queries": opp.get("top_queries", []),
                "keyword": f"{'commercial ' if is_commercial else ''}painters {suburb}",
                "filename": slug.lstrip("/"),
                "template_type": "commercial" if is_commercial else "residential",
            })

    # 2. Missing pages from service × suburb clustering
    for gap in analysis.get("missing_pages", []):
        slug = gap.get("suggested_page", "")
        if slug and slug not in existing_slugs and not os.path.isfile(os.path.join(repo_root, slug.lstrip("/"))):
            suburb = gap["suburb"]
            service = gap["service"]
            queries_text = " ".join(gap.get("top_queries", []))
            is_commercial = any(w in queries_text for w in ["commercial", "industrial", "warehouse", "office"])
            candidates.append({
                "suburb": suburb,
                "impressions": gap["total_impressions"],
                "clicks": gap.get("total_clicks", 0),
                "top_queries": gap.get("top_queries", []),
                "keyword": f"{service} {suburb}",
                "filename": slug.lstrip("/"),
                "template_type": "commercial" if is_commercial else "residential",
            })

    if not candidates:
        return None

    # Return the highest-impression candidate
    return sorted(candidates, key=lambda c: c["impressions"], reverse=True)[0]


def generate_new_page(opportunity, repo_root):
    """
    Generate a complete new landing page using Claude.

    Returns the HTML content string or None on failure.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("   ⚠ ANTHROPIC_API_KEY not set — skipping page generation")
        return None

    # Pick template
    if opportunity["template_type"] == "commercial":
        template_file = "wingfield.html"
    else:
        template_file = "mawson-lakes.html"

    template_path = os.path.join(repo_root, template_file)
    if not os.path.isfile(template_path):
        print(f"   ⚠ Template not found: {template_path}")
        return None

    with open(template_path, "r", encoding="utf-8") as f:
        template_html = f.read()

    client = anthropic.Anthropic(api_key=api_key)
    suburb = opportunity["suburb"].title()
    filename = opportunity["filename"]
    keyword = opportunity["keyword"]
    top_queries = opportunity.get("top_queries", [])

    system_prompt = f"""You are a web developer creating a new landing page for M&K Painting Services ({SITE_URL}).

You will be given an existing page as a template. Your job is to create a NEW page for {suburb} by adapting the template.

CRITICAL RULES:
- Output ONLY the complete HTML — no explanation, no markdown fences, just the raw HTML
- Keep the EXACT same HTML structure, CSS classes, nav, footer, scripts, and layout
- Change ALL content to be specific to {suburb} — do NOT leave any references to the template suburb
- Update: title tag, meta description, canonical URL, OG tags, JSON-LD schemas (geo coords, areaServed), h1, all body content, FAQ questions/answers, project log entries
- The canonical URL must be: {SITE_URL}{filename}
- The page filename is: {filename}
- Target keyword: "{keyword}"
- Related search queries: {', '.join(f'"{q}"' for q in top_queries[:5])}
- JSON-LD geo coordinates must be realistic for {suburb}, South Australia
- FAQ questions must be specific to {suburb} — not generic
- Project log entries should reference {suburb} streets/landmarks
- Include 3-4 internal links to other M&K pages in the "More Areas We Serve" section
- Keep the same web3forms access key, phone number (0405 352 932), and licence details (BLD251492)
- BreadcrumbList schema position 2 name should be: "Painters {suburb}" (or "Commercial Painters {suburb}" for commercial)
- Footer links: Services (/#services), About Us, Contact Us, Privacy Policy"""

    user_prompt = f"""Create a new landing page for {suburb} based on this template.

Target keyword: "{keyword}"
Related queries people search for: {', '.join(f'"{q}"' for q in top_queries[:5])}

Here is the template HTML to adapt:

{template_html}"""

    try:
        message = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=MAX_TOKENS * 4,  # 16384 — full pages need more tokens
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        html = message.content[0].text.strip()

        # Strip markdown fences if Claude wrapped the output
        if html.startswith("```"):
            html = re.sub(r"^```(?:html)?\s*", "", html)
            html = re.sub(r"\s*```$", "", html)

        # Basic validation
        if "<html" not in html or "</html>" not in html:
            print("   ⚠ Generated HTML looks invalid — missing <html> tags")
            return None

        return html

    except Exception as e:
        print(f"   ⚠ Page generation failed: {e}")
        return None


def write_new_page(html, opportunity, repo_root):
    """
    Write the new page HTML and update sitemap.xml + config.py.

    Returns list of changed files (relative paths).
    """
    from datetime import datetime

    filename = opportunity["filename"]
    filepath = os.path.join(repo_root, filename)

    # Write the HTML file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"   ✓ Created {filename}")

    changed_files = [filename]

    # Update sitemap.xml
    sitemap_path = os.path.join(repo_root, "sitemap.xml")
    if os.path.isfile(sitemap_path):
        with open(sitemap_path, "r", encoding="utf-8") as f:
            sitemap = f.read()

        date_str = datetime.now().strftime("%Y-%m-%d")
        new_entry = (
            f"  <url>\n"
            f"    <loc>{SITE_URL.rstrip('/')}/{filename}</loc>\n"
            f"    <lastmod>{date_str}</lastmod>\n"
            f"    <priority>0.85</priority>\n"
            f"  </url>\n"
        )
        sitemap = sitemap.replace("</urlset>", f"{new_entry}</urlset>")

        with open(sitemap_path, "w", encoding="utf-8") as f:
            f.write(sitemap)
        print(f"   ✓ Added {filename} to sitemap.xml")
        changed_files.append("sitemap.xml")

    # Update config.py EXISTING_PAGES
    config_path = os.path.join(repo_root, "seo-agent", "config.py")
    if os.path.isfile(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            config = f.read()

        slug = f"/{filename}"
        keyword = opportunity["keyword"]
        # Insert before the closing brace of EXISTING_PAGES
        new_line = f'    "{slug}": "{keyword}",\n'
        # Find the last entry before the closing }
        config = config.replace(
            '\n}\n\n# ── Analysis thresholds',
            f'\n{new_line}}}\n\n# ── Analysis thresholds',
        )

        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config)
        print(f"   ✓ Added {slug} to config.py EXISTING_PAGES")
        changed_files.append("seo-agent/config.py")

    return changed_files


def create_new_page_pr(opportunity, changed_files, repo_root):
    """
    Create a PR for a new landing page.

    Returns (pr_url, pr_number) or (None, None).
    """
    from datetime import datetime

    date_str = datetime.now().strftime("%Y-%m-%d")
    time_str = datetime.now().strftime("%H%M")
    suburb_slug = opportunity["suburb"].replace(" ", "-")
    branch_name = f"new-page-{suburb_slug}-{date_str}-{time_str}"

    try:
        _run_git(repo_root, "checkout", "-b", branch_name)

        for f in changed_files:
            _run_git(repo_root, "add", f)

        suburb = opportunity["suburb"].title()
        commit_msg = (
            f"Add new landing page: {suburb}\n\n"
            f"  - Created {opportunity['filename']} targeting \"{opportunity['keyword']}\"\n"
            f"  - Updated sitemap.xml\n"
            f"  - Updated config.py EXISTING_PAGES\n"
            f"  - Based on {opportunity['impressions']} impressions in GSC data\n\n"
            f"Generated by MK Painting SEO Agent"
        )

        _run_git(repo_root, "commit", "-m", commit_msg)
        _run_git(repo_root, "push", "-u", "origin", branch_name)

        pr_title = f"SEO: new {suburb} landing page — {opportunity['impressions']} impressions"
        pr_body = (
            f"## New Landing Page: {suburb}\n\n"
            f"The SEO agent detected search demand for **{suburb}** with no dedicated page:\n\n"
            f"- **{opportunity['impressions']}** impressions across **{len(opportunity.get('top_queries', []))}** queries\n"
            f"- Top queries: {', '.join(f'`{q}`' for q in opportunity.get('top_queries', [])[:5])}\n"
            f"- Target keyword: `{opportunity['keyword']}`\n\n"
            f"### Files\n"
            f"- `{opportunity['filename']}` — new landing page\n"
            f"- `sitemap.xml` — added URL entry\n"
            f"- `seo-agent/config.py` — added to EXISTING_PAGES\n\n"
            f"### Review Checklist\n"
            f"- [ ] Content is accurate for {suburb}\n"
            f"- [ ] Phone number and licence details correct\n"
            f"- [ ] JSON-LD schema geo coordinates are realistic\n"
            f"- [ ] Internal links work\n\n"
            f"---\n"
            f"*Generated by MK Painting SEO Agent*"
        )

        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", pr_title,
                "--body", pr_body,
                "--base", "main",
                "--head", branch_name,
            ],
            capture_output=True, text=True, cwd=repo_root,
        )

        if result.returncode == 0:
            pr_url = result.stdout.strip()
            pr_number = pr_url.rstrip("/").split("/")[-1]
            return pr_url, pr_number

        print(f"   ⚠ PR creation failed: {result.stderr}")
        return None, None

    except Exception as e:
        print(f"   ⚠ Git/PR error: {e}")
        return None, None

    finally:
        try:
            _run_git(repo_root, "checkout", "main")
        except Exception:
            pass


def _build_pr_body(changes):
    """Build PR description markdown."""
    lines = [
        "## SEO Optimizations\n",
        "Changes generated by the MK Painting SEO Agent based on Google Search Console data.\n",
        "### Changes\n",
        "| File | Type | Description |",
        "|---|---|---|",
    ]

    for c in changes:
        lines.append(f"| `{c['file']}` | {c['change_type']} | {c['description']} |")

    lines.extend([
        "",
        "### Review Checklist",
        "- [ ] Title tags are under 60 characters",
        "- [ ] Meta descriptions are 120-155 characters",
        "- [ ] Changes match the target keywords",
        "",
        "---",
        "*Generated by MK Painting SEO Agent*",
    ])

    return "\n".join(lines)
