"""
SEO change implementer.

Takes Claude's structured recommendations and applies them
directly to the HTML files. Creates a branch and PR for review.
"""

import json
import os
import re
import subprocess

import anthropic

from config import CLAUDE_MODEL, EXISTING_PAGES, MAX_TOKENS, SITE_URL


def generate_changes(analysis, repo_root=None):
    """
    Send analysis to Claude and get back structured changes to implement.

    Returns list of dicts:
        {file, change_type, old_value, new_value, description}
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("   ⚠ ANTHROPIC_API_KEY not set — skipping implementation")
        return []

    # Read current title/meta from HTML files so Claude knows exact values
    current_tags = _read_current_tags(repo_root) if repo_root else {}

    client = anthropic.Anthropic(api_key=api_key)

    system_prompt = _build_system_prompt(current_tags)
    user_prompt = _build_change_request(analysis)

    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=MAX_TOKENS,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )

    return _parse_changes(message.content[0].text)


def apply_changes(changes, repo_root):
    """
    Apply the list of changes to HTML files.

    Returns list of successfully applied changes.
    """
    applied = []

    for change in changes:
        file_rel = change["file"].lstrip("/")

        # Handle homepage — "/" maps to index.html
        if not file_rel or file_rel == "/":
            file_rel = "index.html"

        # Must be an HTML file
        if not file_rel.endswith(".html"):
            print(f"   ⚠ Skipping non-HTML file: {file_rel}")
            continue

        filepath = os.path.join(repo_root, file_rel)

        if not os.path.isfile(filepath):
            print(f"   ⚠ File not found: {filepath}")
            continue

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        old = change["old_value"]
        new = change["new_value"]

        if old not in content:
            # Try case-insensitive match for meta/title tags
            pattern = re.compile(re.escape(old), re.IGNORECASE)
            if pattern.search(content):
                content = pattern.sub(new, content, count=1)
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                applied.append(change)
                print(f"   ✓ {change['change_type']}: {change['file']} (case-insensitive)")
            else:
                print(f"   ⚠ Could not find old value in {change['file']}")
        else:
            content = content.replace(old, new, 1)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            applied.append(change)
            print(f"   ✓ {change['change_type']}: {change['file']}")

    return applied


def create_pr(changes, repo_root):
    """
    Create a git branch, commit changes, push, and open a PR.

    Returns (pr_url, pr_number) or (None, None) on failure.
    """
    from datetime import datetime

    date_str = datetime.now().strftime("%Y-%m-%d")
    branch_name = f"seo-updates-{date_str}"

    try:
        _run_git(repo_root, "checkout", "-b", branch_name)

        # Stage only the changed HTML files
        changed_files = list(set(c["file"].lstrip("/") for c in changes))
        for f in changed_files:
            _run_git(repo_root, "add", f)

        # Build commit message
        summary_lines = [f"  - {c['description']}" for c in changes[:10]]
        if len(changes) > 10:
            summary_lines.append(f"  - ...and {len(changes) - 10} more")

        commit_msg = (
            f"SEO optimizations — {date_str}\n\n"
            + "\n".join(summary_lines)
            + "\n\nGenerated by MK Painting SEO Agent"
        )

        _run_git(repo_root, "commit", "-m", commit_msg)
        _run_git(repo_root, "push", "-u", "origin", branch_name)

        # Create PR via gh CLI
        pr_body = _build_pr_body(changes)
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", f"SEO: title/meta optimizations — {date_str}",
                "--body", pr_body,
                "--base", "main",
                "--head", branch_name,
            ],
            capture_output=True, text=True, cwd=repo_root,
        )

        if result.returncode == 0:
            pr_url = result.stdout.strip()
            # Extract PR number from URL
            pr_number = pr_url.rstrip("/").split("/")[-1]
            return pr_url, pr_number

        print(f"   ⚠ PR creation failed: {result.stderr}")
        return None, None

    except Exception as e:
        print(f"   ⚠ Git/PR error: {e}")
        return None, None

    finally:
        # Always switch back to main
        try:
            _run_git(repo_root, "checkout", "main")
        except Exception:
            pass


def _run_git(repo_root, *args):
    """Run a git command in the repo root."""
    result = subprocess.run(
        ["git"] + list(args),
        capture_output=True, text=True, cwd=repo_root,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr}")
    return result.stdout.strip()


def _read_current_tags(repo_root):
    """Read the current <title> and <meta description> from each HTML page."""
    tags = {}

    for slug in EXISTING_PAGES:
        file_rel = slug.lstrip("/")
        if not file_rel:
            file_rel = "index.html"
        if not file_rel.endswith(".html"):
            continue

        filepath = os.path.join(repo_root, file_rel)
        if not os.path.isfile(filepath):
            continue

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        # Extract <title>...</title>
        title_match = re.search(r"<title>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
        # Extract <meta name="description" content="...">
        meta_match = re.search(
            r'<meta\s+name=["\']description["\']\s+content=["\']([^"\']*)["\']',
            content, re.IGNORECASE,
        )

        tags[slug] = {
            "file": file_rel,
            "title": title_match.group(0) if title_match else None,
            "title_text": title_match.group(1).strip() if title_match else None,
            "meta": meta_match.group(0) if meta_match else None,
            "meta_text": meta_match.group(1).strip() if meta_match else None,
        }

    return tags


def _build_system_prompt(current_tags=None):
    pages_info = []
    for slug, kw in EXISTING_PAGES.items():
        line = f"- `{slug}` → target: \"{kw}\""
        if current_tags and slug in current_tags:
            t = current_tags[slug]
            if t["title"]:
                line += f"\n  Current title: `{t['title']}`"
            if t["meta"]:
                line += f"\n  Current meta: `{t['meta']}`"
        pages_info.append(line)

    pages_str = "\n".join(pages_info)

    return f"""You are an SEO implementation agent for M&K Painting Services ({SITE_URL}).

Existing pages, their target keywords, and CURRENT HTML tags:
{pages_str}

Your job is to output SPECIFIC changes to HTML files based on GSC performance data.

CRITICAL RULES:
- Only suggest title tag and meta description changes (safe, high-impact, low-risk)
- Output valid JSON array — no markdown, no explanation, just the JSON
- Each change must have: file, change_type, old_value, new_value, description
- old_value must be the EXACT current HTML string copied from above — character for character
- new_value must be the replacement HTML string
- For title changes: old_value = `<title>Current Title</title>`, new_value = `<title>New Title</title>`
- For meta changes: old_value = the full `<meta name="description" content="...">` tag, new_value = the new full tag
- Title tags must be under 60 characters
- Meta descriptions must be 120-155 characters
- Only suggest changes where CTR data shows a clear problem
- Maximum 5 changes per run — focus on highest impact only
- The "file" field must be the HTML filename like "west-lakes.html" (not a slug like "/west-lakes.html")"""


def _build_change_request(analysis):
    parts = ["Here is today's GSC analysis. Output a JSON array of changes to implement.\n"]

    # CTR gaps
    ctr = analysis.get("ctr_gaps", [])[:10]
    if ctr:
        parts.append("**CTR Gaps (underperforming vs benchmark):**")
        for g in ctr:
            parts.append(
                f"- \"{g['query']}\" — pos {g['position']}, CTR {g['ctr']:.1%} "
                f"vs expected {g['expected_ctr']:.0%}, +{g['potential_clicks']} potential clicks"
            )

    # Zero click
    zc = analysis.get("zero_click", [])[:5]
    if zc:
        parts.append("\n**Zero-Click (impressions but no clicks):**")
        for z in zc:
            parts.append(f"- \"{z['query']}\" — {z['impressions']} imp, pos {z['position']}")

    # Striking distance
    sd = analysis.get("striking_distance", [])[:5]
    if sd:
        parts.append("\n**Striking Distance (pos 4-15):**")
        for kw in sd:
            parts.append(
                f"- \"{kw['query']}\" — pos {kw['position']}, {kw['impressions']} imp"
            )

    parts.append(
        '\n\nOutput format — JSON array only, no markdown:\n'
        '[{"file": "/page.html", "change_type": "title", '
        '"old_value": "<title>Old Title</title>", '
        '"new_value": "<title>New Title</title>", '
        '"description": "Why this change helps"}]'
    )

    return "\n".join(parts)


def _parse_changes(text):
    """Parse Claude's response into a list of change dicts."""
    # Try to find JSON array in the response
    text = text.strip()

    # Remove markdown code fences if present
    if "```" in text:
        match = re.search(r"```(?:json)?\s*(\[.*?\])\s*```", text, re.DOTALL)
        if match:
            text = match.group(1)

    # Try to find a JSON array
    start = text.find("[")
    end = text.rfind("]") + 1
    if start >= 0 and end > start:
        text = text[start:end]

    try:
        changes = json.loads(text)
        if not isinstance(changes, list):
            return []

        # Validate each change has required fields
        valid = []
        for c in changes:
            if all(k in c for k in ("file", "change_type", "old_value", "new_value", "description")):
                valid.append(c)

        return valid[:5]  # Max 5 changes per run

    except json.JSONDecodeError:
        print(f"   ⚠ Could not parse Claude's response as JSON")
        return []


def _build_pr_body(changes):
    """Build PR description markdown."""
    lines = [
        "## SEO Optimizations\n",
        "Changes generated by the MK Painting SEO Agent based on Google Search Console data.\n",
        "### Changes\n",
        "| File | Type | Description |",
        "|---|---|---|",
    ]

    for c in changes:
        lines.append(f"| `{c['file']}` | {c['change_type']} | {c['description']} |")

    lines.extend([
        "",
        "### Review Checklist",
        "- [ ] Title tags are under 60 characters",
        "- [ ] Meta descriptions are 120-155 characters",
        "- [ ] Changes match the target keywords",
        "",
        "---",
        "*Generated by MK Painting SEO Agent*",
    ])

    return "\n".join(lines)
